# Configuration for Travis CI
language: cpp
os: linux
sudo: required
dist: trusty
cache: ccache

before_install:
    - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
    - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
    - sudo apt-get -qq update
    - sudo apt-get -y install cmake libsdl2-dev libsdl2-mixer-dev libxrandr-dev libxxf86vm-dev libfluidsynth-dev ncurses-dev 
    - sudo apt-get -y install qt55base qt55imageformats qt55x11extras

before_script:
    - mkdir build-travis

script:
    - source /opt/qt55/bin/qt55-env.sh
    - cd build-travis && cmake -DQMAKE=/opt/qt55/bin/qmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDENG_ENABLE_TESTS=ON ../doomsday && make -j4

notifications:
    slack: dengteam:A4Hl4awsyxNxQG61rrWgDuHo
