# Configuration for Travis CI
language: cpp
os: linux
before_install:
    - sudo add-apt-repository ppa:george-edison55/precise-backports -y
    - sudo apt-get -qq update
    - sudo apt-get install cmake cmake-data
before_script:
    - mkdir build-travis
script:
    - cd build-travis && cmake ../doomsday && make
